# ZenML configuration for Streamlit Cloud
[zenml]
# Use local SQLite database
store_type = "local"
store_path = ".zen/local/store"

# Disable telemetry to prevent connection issues
disable_analytics = true

# Disable rich console output
no_color = true

# Disable update checks
disable_update_check = true
